### PR TITLE
New version of metadata

### PR DESCRIPTION
**Pull request by KillariDev**
- new coingecko list
- run process again, so new v2/v3 pools
- ENS erc1155 token (fixes https://github.com/DarkFlorist/address-metadata/issues/12 )
- permit2 contract
- all images are now converted to PNG
- all images are scaled to same size
- retrieve NFT's from alchemy instead from opensea
- separate NFT's to ERC721's and ERC1155's

### CODE REVIEW

**Review by MicahZoltu — DISMISSED** [review]

**Comment by jubalm** [comment]
one of the nft image is a blank png `0x6f38b6b808e68e031f11bf9d321c6085aedda185`, looking at opensea search, there's only account and no collection

**Comment by jubalm** [comment]
nft image `0xe86f1be637c4f404f4f53ed327a80a1063eee5f7.png` is an empty file and could not be rendered

**Review by jubalm — APPROVED** [review]
Might want to investigate on the blank images as something that we could improve on the fetch algo

**Comment by KillariDev** [comment]
> 0x6f38b6b808e68e031f11bf9d321c6085aedda185

https://nft.coinbase.com/nft/ethereum/0x6f38b6b808e68e031f11bf9d321c6085aedda185/417 coinbase has it

**Comment by KillariDev** [comment]
> Might want to investigate on the blank images as something that we could improve on the fetch algo

blank images are expected and ok. We shouldn't have any empty images thought, that feels like a bug

**Pull request merged**
